### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joernalraun** [CalliTGS3/pxt-calliope-sim7020e#1]
It would be great if you could add an MIT license to your extensions! From now on only extensions with an MIT license will be able to be submitted into MakeCode (and it is vey likely that this will come for external extensions as well).
Thanks for the great work! :)

**Comment by CalliTGS3** [comment]
MIT license created

**Comment by joernalraun** [comment]
Great! Would you mind adding the same license to the others as well (I could see that some have them, but most don't). Especially this one: https://github.com/CalliTGS3/pxt-calliope-sparkfunQwiicOpenLog would help a couple of people.
Thanks!
